#!/bin/bash

# Activate my virtualenv for packages like BioPython and envoy.  
# More info about virtualenv at: janalysis/virtualenv
source activate m4_janalysis

python mummer_all_bins.py
# Note: mummer_all_bins.py makes ./support_files/bins_available.csv 
# if it doesn't already exist
